<?php


namespace App\Data\Shop\Order;


class OrderItemModelProxy extends OrderItemModel
{

    /**
     * @var OrderItemModel
     */
    private $model;

    /**
     * @var OrderItemRepository
     * @onInit(App\Data\Shop\Order\OrderItemRepository)
     */
    private $repository;


    public function getAmount(): int
    {
        if (!$this->isModelInited()) {
            $this->initModel();
        }

        return $this->model->getAmount(); // TODO: Change the autogenerated stub
    }

    public function getTotalSum(): float
    {
        if (!$this->isModelInited()) {
            $this->initModel();
        }

        return $this->model->getTotalSum(); // TODO: Change the autogenerated stub
    }

    private function isModelInited() {
        return !is_null($this->model);
    }

    private function initModel() {
        $id = $this->getId();

        $this->model = $this->repository->find($id);
    }


}